apiVersion: v1
data:
  application.yaml: |-
    name: armor
    gh_auth: eWFyYTo2MDYzNzcxMTc3MGY5ZDAwMDRlYWVlNDVhOGYwZmZkNmYyYjM0YTlk
    mode : internal
kind: ConfigMap
metadata:
  name: application
  namespace: {{ .Values.namespace.name }}