{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ .Values.rbac.role.name}}
    namespace: {{ .Values.namespace.name }}
rules:
    - apiGroups:
          - "*"
      resources:
          - "*"
      verbs:
          - get
          - list
{{end}}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ .Values.rbac.binding.name}}
subjects:
    - kind: ServiceAccount
      name: {{ .Values.serviceAccount.name }}
      namespace: {{ .Values.namespace.name }}
roleRef:
    kind: ClusterRole
    name: {{ .Values.rbac.role.name}}
    apiGroup: rbac.authorization.k8s.io
{{end}}