{{- if .Values.secret.kubeconfig.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kubeconfig
  namespace: {{ .Values.namespace }}
data:
  kubeconfig: {{ .Files.Get "./config" | b64enc }}
{{ end  }}
---
{{- if .Values.secret.registrykey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: registrykey
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Files.Get "./registrykey" | b64enc }}
type: kubernetes.io/dockerconfigjson
{{ end }}