{{- if .Values.secret.kubeconfig.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kubeconfig
  namespace: {{ .Values.namespace.name }}
data:
  kubeconfig: {{ .Files.Get "./config" | b64enc }}
{{ end  }}
---
{{- if .Values.secret.registrykey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: registrykey
  namespace: {{ .Values.namespace.name }}
data:
  .dockerconfigjson: {{ .Files.Get "./registrykey" | b64enc }}
type: kubernetes.io/dockerconfigjson
{{ end }}
---
{{- if .Values.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: app-env-secret
  namespace: {{ .Values.namespace.name }}
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }} : {{ $val | b64enc }}
  {{- end}}
{{ end  }}