{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: "{{.Chart.Name}}-service"
  namespace: {{ .Values.namespace.name }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: "TCP"
    port: {{ .Values.port }}
  selector:
    app: {{ .Values.selector }}
  type: LoadBalancer
{{- end }}