{
 "title": "A.R.M.O.R. installation view",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(armor_metrics, installation)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Critical severity items",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count (armor_metrics{severity=\"critical\", installation=\"$installation\"})  or vector(0)"
    }
   ]
  },
  {
   "title": "Applications with version lag",
   "type": "table",
   "gridPos": { "h": 21, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "armor_metrics{installation=\"$installation\"}"
    }
   ]
  },
  {
   "title": "Major severity items",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"major\", installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Moderate severity items",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"moderate\", installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Low severity items",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"low\", installation=\"$installation\"}) or vector(0)"
    }
   ]
  }
 ]
}