{
 "title": "A.R.M.O.R. installation view",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "installation",
    "query": "label_values(armor_metrics, installation)"
   }
  ]
 },
 "panels": [
  {
   "title": "Critical severity in Major Channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"critical\", channel=\"major\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Critical severity in Minor Channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"critical\", channel=\"minor\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Critical Severity in Release channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"critical\", channel=\"release\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Critical severity in Build channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"critical\", channel=\"build\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Major severity in Major channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"major\", channel=\"major\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Major severity in Minor channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"major\", channel=\"minor\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Major severity in Release channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"major\", channel=\"release\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Major severity in Build channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"major\", channel=\"build\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Moderate severity in Major channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"moderate\", channel=\"major\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Moderate severity in Minor channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"moderate\", channel=\"minor\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Moderate severity in Release channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"moderate\", channel=\"release\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Moderate severity in Build channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"moderate\", channel=\"build\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Low severity in Major channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"low\", channel=\"major\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Low severity in Minor channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"low\", channel=\"minor\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Low severity in Release channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"low\", channel=\"release\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Low severity in Build channel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "count(armor_metrics{severity=\"low\", channel=\"build\",installation=\"$installation\"}) or vector(0)"
    }
   ]
  }
 ]
}