{
 "title": "A.R.M.O.R  organization view",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Installations severity index",
   "type": "table",
   "gridPos": { "h": 23, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (installation) ((count by (installation, severity) (armor_metrics)) * (sum by (installation, severity) (severity_factor)))) / (count by (installation) (armor_metrics))",
     "legendFormat": "{{installation}}"
    }
   ]
  },
  {
   "title": "Critical issues",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (installation) (armor_metrics{severity=\"critical\"})"
    }
   ]
  },
  {
   "title": "Major Issues",
   "type": "graph",
   "gridPos": { "h": 1, "w": 6, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (installation) (armor_metrics{severity=\"major\"})"
    }
   ]
  },
  { "title": "A.R.M.O.R alerts", "type": "alertlist", "gridPos": { "h": 23, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "Overall number of issues",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 22, "w": 12, "x": 5, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (installation, severity) (armor_metrics)",
     "legendFormat": "Installation: {{installation}} , severity {{severity}}"
    }
   ]
  }
 ]
}